cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.remove_from_cart, name='cart_remove'),
    path('', views.cart_detail, name='cart_detail')
]

online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('', views.products_list, name='products_list'),
    path('<slug:category_slug>/', views.products_list, name='products_list_by_category'),
    path('<int:id>/<slug>', views.product_detail, name='product_detail')
]

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models
from products.models import Product


class Order(models.Model):
    first_name = models.CharField(max_length=120)
    last_name = models.CharField(max_length=120)
    email = models.EmailField()
    address = models.CharField(max_length=200)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=60)
    paid = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created', )

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

    def __str__(self):
        return f"Order {self.id}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def get_cost(self):
        return self.price * self.quantity

    def __str__(self):
        return self.id

products/models.py
from django.db import models
from django.utils.text import slugify
from django.shortcuts import reverse


class Category(models.Model):
    name = models.CharField(max_length=120)
    slug = models.SlugField(max_length=120, db_index=True, unique=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ('name',)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('products:products_list_by_category', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=120)
    description = models.TextField(max_length=1000, blank=True)
    slug = models.SlugField(max_length=120, db_index=True, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        # index_together = (('id', 'slug'),)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('products:product_detail', args=[self.id, self.slug])

    def __str__(self):
        return self.name

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 31)]


class CartAddItemForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(initial=False, required=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from cart.cart import Cart
from cart.forms import CartAddItemForm
from products.models import Product


# @require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddItemForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


# @require_POST
def remove_from_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddItemForm(initial={'quantity': item['quantity'],
                                                                'update': True})
    return render(request, 'cart/cart_detail.html', {'cart': cart})

orders/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
from django.shortcuts import render, get_object_or_404
from products.models import Product, Category
from cart.forms import CartAddItemForm

def index(request):
    return render(request, 'products/index.html')


def products_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    context = {'category': category, 'categories': categories, 'products': products}
    return render(request, 'products/products_list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddItemForm()
    return render(request, 'products/product_detail.html', {'product': product, 'cart_product_form': cart_product_form})

cart/templates/cart/cart_detail.html
{% extends 'products/base.html' %}
{% load static %}

{% block content %}
<head>
    <link href="{% static 'css/cart.css' %}" rel="stylesheet">
</head>

<div class="card">
            <div class="row">
                <div class="col-md-8 cart">
                    <div class="title">
                        <div class="row">
                            <div class="col"><h4><b>Shopping Cart</b></h4></div>
                            <div class="col align-self-center text-right text-muted">{{cart.total_items}} items</div>
                        </div>
                    </div>
                    {% for item in cart %}
                    {% with product=item.product %}
                    <div class="row border-top border-bottom">
                        <div class="row main align-items-center">
                            <div class="col-2"><img class="img-fluid" src="{{product.image.url}}"></div>
                            <div class="col">
                                <div class="row">{{product.name}}</div>
<!--                                <div class="row">Quality product</div>-->
                            </div>
                            <div class="col">
                                <form action="{% url 'cart:cart_add' product.id %}" method="post">{{item.quantity}} item{{ item.quantity|pluralize }} </form>
<!--                                <input type="submit" value="Update">-->
                                {% csrf_token %}
                            </div>
<!--                            <div class="col"><a href="{% url 'cart:cart_remove' product.id %}"> <input type="submit" value="Update"></a></div>-->
<!--                            <div class="col"><a href="{% url 'cart:cart_add' product.id %}">Update</a></div>-->
                            <div class="col"><a href="{% url 'cart:cart_remove' product.id %}">Remove</a></div>
                            <div class="col">${{item.total_price}}</div>
                        </div>
                    </div>
                    {% endwith %}
                    {% endfor %}
<!--                    <div class="row">-->
<!--                        <div class="row main align-items-center">-->
<!--                            <div class="col-2"><img class="img-fluid" src="https://i.imgur.com/ba3tvGm.jpg"></div>-->
<!--                            <div class="col">-->
<!--                                <div class="row text-muted">Shirt</div>-->
<!--                                <div class="row">Cotton T-shirt</div>-->
<!--                            </div>-->
<!--                            <div class="col">-->
<!--                                <a href="#">-</a><a href="#" class="border">1</a><a href="#">+</a>-->
<!--                            </div>-->
<!--                            <div class="col">&euro; 44.00 <span class="close">&#10005;</span></div>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                    <div class="row border-top border-bottom">-->
<!--                        <div class="row main align-items-center">-->
<!--                            <div class="col-2"><img class="img-fluid" src="https://i.imgur.com/pHQ3xT3.jpg"></div>-->
<!--                            <div class="col">-->
<!--                                <div class="row text-muted">Shirt</div>-->
<!--                                <div class="row">Cotton T-shirt</div>-->
<!--                            </div>-->
<!--                            <div class="col">-->
<!--                                <a href="#">-</a><a href="#" class="border">1</a><a href="#">+</a>-->
<!--                            </div>-->
<!--                            <div class="col">&euro; 44.00 <span class="close">&#10005;</span></div>-->
<!--                        </div>-->
<!--                    </div>-->
                    <div class="back-to-shop"><a href="{% url 'products:products_list' %}">&leftarrow;</a><span class="text-muted">Back to shop</span></div>
                </div>
                <div class="col-md-4 summary">
                    <div><h5><b>Summary</b></h5></div>
                    <hr>
                    <div class="row">
                        <div class="col" style="padding-left:0;">ITEMS {{cart.total_items}}</div>
                        <div class="col text-right">${{cart.get_total_price}}</div>
                    </div>
                    <form>
<!--                        <p>SHIPPING</p>-->
<!--                        <select><option class="text-muted">Standard-Delivery- &euro;5.00</option></select>-->
                        <p> GIVE COUPON CODE</p>
                        <input id="code" placeholder="Enter your code">
                    </form>
                    <div class="row" style="border-top: 1px solid rgba(0,0,0,.1); padding: 2vh 0;">
                        <div class="col">TOTAL PRICE</div>
                        <div class="col text-right">${{cart.get_total_price}}</div>
                    </div>
                    <button class="btn" type="submit">CHECKOUT</button>
                </div>
            </div>

        </div>
{% endblock content %}

products/templates/products/base.html
{% load static %}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Shop Homepage - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet">
        <link href="{% static 'css/categories.css' %}" rel="stylesheet">

        <link href="https://fonts.googleapis.com/css?family=Great+Vibes|Open+Sans|Playfair+Display" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
        <link href="{% static 'fonts/fontawesome-all.min.css' %}" rel="stylesheet" type="text/css">

    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'products:products_list' %}">Online Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular products</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'products:products_list' %}">Products</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'products:products_list' %}">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                {% for c in categories%}
                                    <li {% if category.slug == c.slug %}{% endif %}><a class="dropdown-item" href="{{ c.get_absolute_url }}">{{c.name}}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
<!--                        <li class="nav-item"><a class="nav-link" href="#!">Categories</a></li>-->
                    </ul>
                    <form class="d-flex" action="{% url 'cart:cart_detail' %}">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            {% if not cart|length > 0 %}
                            Cart<span class="badge bg-dark text-white ms-1 rounded-pill">{{ cart.total_items }} item{{ cart.total_items|pluralize }},
                                ${{ cart.get_total_price }}
                             </span>
                            {% else %}
                            Your cart is empty
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Cozy Shop</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Choose any product you wanna buy and we will
                    deliver it as soon as possible!</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        {% block content %}{% endblock content %}
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Online Shop 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

products/templates/products/index.html
{% extends 'products/base.html' %}

{% block content %}
<h1>hello</h1>
{% endblock %}

products/templates/products/product_detail.html
{% extends 'products/base.html' %}
{% load static %}

{% block title %}{{product.name}}{% endblock %}

{% block content %}
<head xmlns="http://www.w3.org/1999/html">
    <link href="{% static 'css/product.css' %}" rel="stylesheet">
</head>
    <div class="container py-4 my-4 mx-auto d-flex flex-column">
    <div class="header">
        <div class="row r1">
            <div class="col-md-9 abc">
                <h1>{{product.name}}</h1>
            </div>
<!--            <div class="col-md-3 text-right pqr"><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></div>-->
            <h4 class="text-right para">Product price: ${{product.price}}</h4>
        </div>
    </div>
    <div class="container-body mt-4">
        <div class="row r3">
            <div class="col-md-5 p-0 klo">
                <ul>
                    <li>{{product.description}}</li>
                    <li>Free Shipping</li>
                    <li>Easy Returns</li>
                    <li>High quality</li>
                    <li>EMI Starting from (On Credit Cards)</li>
                    <li>Normal Delivery : 2-3 Days</li>
                    <li>Express Delivery : 1-2 Days</li>
                    <li>COD Available (All Over Belarus)</li>
                </ul>
            </div>
            <div class="col-md-7"> <img src="{{product.image.url}}" width="90%" height="95%"> </div>
        </div>
    </div>
    <div class="footer d-flex flex-column mt-5">
        <div class="row r4">
            <div class="col-md-2 myt des"><a href="#">Description</a></div>
<!--            <div class="col-md-2 myt "><a href="#">Review</a></div>-->
            <div class="col-md-2 mio offset-md-4">
                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                    {{ cart_product_form }}
                    {% csrf_token %}
                    <input type="submit" value="Add to cart">
                </form>
            </div>
<!--            <div class="col-md-2 myt "><button type="button" class="btn btn-outline-warning"><a href="#">BUY NOW</a></button></div>-->
        </div>
    </div>
</div>
{% endblock %}

products/templates/products/products_list.html
{% extends 'products/base.html' %}
{% block title %}Products{% endblock %}

{% block content %}
<section class="py-5">
<!--            <div class="container-fluid d-flex h-100 justify-content-center align-items-center p-0">-->
<!--            <div class="card center" style="width: 18rem;">-->
<!--                <a class="d-block" href="#"><img class="d-block" src="https://westerngrocer.com/wp-content/uploads/2016/10/Shopping-Cart-Logo-lg-891x1024.jpg" alt="Headphones"></a>-->
<!--                <div class="card-body pb-2">-->
<!--                    <h3 class="h6 mb-2">Categories</h3><span class="d-block mb-3 font-size-xs text-muted">Starting from <span class="font-weight-semibold">$2</span></span>-->
<!--                    <div class="list-group list-group-flush font-size-sm">{% if not category %}<a class="list-group-item list-group-item-action" href="products:products_list">All<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right ml-1" style="width: .875rem; height: .875rem;"><polyline points="9 18 15 12 9 6"></polyline></svg></a>{% endif %}{% for c in categories %}<li class="list-group-item list-group-item-action" {% if category.slug == c.slug %}{% endif %}><a href="{{ c.get_absolute_url }}">{{ c.name }}<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right ml-1" style="width: .875rem; height: .875rem;"><polyline points="9 18 15 12 9 6"></polyline></svg></a>{% endfor %}</div>-->
<!--                </div>-->
<!--                </div>-->
<!--            </div>-->
            <h1 class="text-center">{% if category %}{{ category.title }}{% else %}Products{% endif %}</h1>
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% for product in products %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Sale badge-->
                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                            <!-- Product image-->
                            <img class="card-img-top" src="{{product.image.url}}" alt="..." height="150"  />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{product.name}}</h5>
                                    <!-- Product reviews-->
                                    <div class="d-flex justify-content-center small text-warning mb-2">
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                        <div class="bi-star-fill"></div>
                                    </div>
                                    <!-- Product price-->
                                    <span class="text-muted text-decoration-line-through"></span>
                                    ${{product.price}}
                                </div>

                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{{ product.get_absolute_url }}">View</a><form action="{% url 'cart:cart_add' product.id %}" class="btn btn-outline-dark mt-auto" method="post">Add</form></div>
                            </div>

                        </div>
                    </div>
                    {% endfor %}
                    </div>
                </div>
            </div>
        </section>
{% endblock %}